package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"strconv"
)

var tmpl = `package mps

// THIS FILE WAS GENERATED BY "kernels/kernels_gen.go" AND CREATED THROUGH
// THE "go generate" COMMAND. DO NOT EDIT.

var (
	pyKernel = []byte(%s)
	rKernel = []byte(%s)
)
`

func main() {
	pykernel, err := ioutil.ReadFile("kernels/pykernel.py")
	if err != nil {
		log.Fatal(err)
	}
	rkernel, err := ioutil.ReadFile("kernels/rkernel.R")
	if err != nil {
		log.Fatal(err)
	}
	py := strconv.Quote(string(pykernel))
	r := strconv.Quote(string(rkernel))
	fmt.Printf(tmpl, py, r)
}
